# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 文溪的博客
email: wenxizhao@163.com
description: > # this means to ignore newlines until "baseurl:"
  善为脚,勤为手,勇为魄,慧为眼,爱为心
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 知乎
github_username:  github

# Build settings
markdown: kramdown
